<template>
    <div class="loading" v-bind:class="{show:{isLoading}}">
        <div class="loadingio-spinner-ball-mv3innpa7tn ">
            <div class="ldio-50tqd501wv">
                <div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'comp-loading',
    props:{
        isLoading: {type: Boolean, default: false},
    }
}
</script>

<style>
.loading{
    position: fixed;
    top:0;
    right: 0;
    left: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.4);
    visibility: hidden;
}
.loading.show{
    visibility: visible;
}
.loading .loadingio-spinner-ball-mv3innpa7tn{
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
}
@keyframes ldio-50tqd501wv {
  0%, 100% {
    animation-timing-function: cubic-bezier(0.45,0,0.9,0.55)
  }
  0% {
    transform: translate(0,0)
  }
  50% {
    transform: translate(0,68px);
    animation-timing-function: cubic-bezier(0,0.45,0.55,0.9);
  }
  100% {
    transform: translate(0,0);
  }
}

.ldio-50tqd501wv div {
  position: absolute;
  width: 92px;
  height: 92px;
  border-radius: 50%;
  background: #007bff;
  left: 54px;
  top: 20px;
  animation: ldio-50tqd501wv 1.0869565217391304s linear infinite;
}
.loadingio-spinner-ball-mv3innpa7tn {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-50tqd501wv {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-50tqd501wv div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>


<style type="text/css">

</style>